In [1]:
# importing torch
import torch

In [2]:
# training input(X) and output(y)
X = torch.Tensor([[1], [2], [3],
                [4], [5], [6]])
y = torch.Tensor([[5], [10], [15],
                  [20], [25], [30]])

In [5]:
X

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])

In [6]:
y

tensor([[ 5.],
        [10.],
        [15.],
        [20.],
        [25.],
        [30.]])

In [3]:
class Model(torch.nn.Module):
 
    # defining layer
    def __init__(self):
        super(Model, self).__init__()
        self.linear = torch.nn.Linear(1, 1)
     
    # implementing forward pass
    def forward(self, x):
        y_pred = self.linear(x)
        return y_pred
 
model = torch.nn.Linear(1 , 1)

In [4]:
# defining loss function and optimizer
loss_fn = torch.nn.L1Loss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.01 )

In [7]:
for epoch in range(1000):
    
    # predicting y using initial weights
    y_pred = model(X.requires_grad_())
 
    # loss calculation
    loss = loss_fn(y_pred, y)
 
    # calculating gradients
    loss.backward()
 
    # updating weights
    optimizer.step()
 
    optimizer.zero_grad()

In [8]:
# testing on new data   
X = torch.Tensor([[7], [8]])
predicted = model(X)
print(predicted)

tensor([[33.7286],
        [38.3034]], grad_fn=<AddmmBackward0>)
