In [123]:
import numpy as np
import pandas as pd
import torch.nn.functional as functional
import torch
# Reading the data
data = pd.read_csv("back.csv")

In [124]:
inputs = data.drop('Temp',axis=1).values
target = data.Temp.values  # target = data['Temp'].values

In [125]:
inputs

array([[ 67,  45,  50],
       [ 50,  35,  40],
       [104,  78,  65],
       [140,  98, 100],
       [ 93,  56,  75],
       [ 79,  43,  55]], dtype=int64)

In [126]:
target

array([ 73,  91,  83,  95,  77, 101], dtype=int64)

In [127]:
inputs = torch.tensor(inputs, dtype=torch.float32)
target = torch.tensor(target, dtype=torch.float32)
target = target.reshape(-1,1)

In [128]:
inputs

tensor([[ 67.,  45.,  50.],
        [ 50.,  35.,  40.],
        [104.,  78.,  65.],
        [140.,  98., 100.],
        [ 93.,  56.,  75.],
        [ 79.,  43.,  55.]])

In [129]:
target

tensor([[ 73.],
        [ 91.],
        [ 83.],
        [ 95.],
        [ 77.],
        [101.]])

In [130]:
w = torch.randn(1, 3, requires_grad=True) # 1 row and 3 column
b = torch.randn(1, requires_grad=True)
print(w)
print(b)

tensor([[-1.4156,  0.1975,  0.8215]], requires_grad=True)
tensor([-2.0141], requires_grad=True)


In [131]:
def model(x):
    return x @ w.t() + b 

In [132]:
prediction = model(inputs)
print(prediction)

tensor([[-46.9016],
        [-33.0253],
        [-80.4413],
        [-98.7031],
        [-60.9990],
        [-60.1766]], grad_fn=<AddBackward0>)


In [133]:
mse = functional.mse_loss
loss = mse(prediction,target)
print(loss)

tensor(23169.0391, grad_fn=<MseLossBackward0>)


In [134]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-27972.6211, -18708.7734, -20054.9082]])
tensor([-300.0823])


In [135]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [136]:
for i in range(10):
    pred = model(inputs)
    error=mse(pred, target)
    print(error)
    print(w)
    error.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

tensor(10451.6836, grad_fn=<MseLossBackward0>)
tensor([[-1.1359,  0.3845,  1.0220]], requires_grad=True)
tensor(4958.4219, grad_fn=<MseLossBackward0>)
tensor([[-0.9519,  0.5071,  1.1540]], requires_grad=True)
tensor(2585.5535, grad_fn=<MseLossBackward0>)
tensor([[-0.8308,  0.5873,  1.2409]], requires_grad=True)
tensor(1560.5153, grad_fn=<MseLossBackward0>)
tensor([[-0.7511,  0.6396,  1.2981]], requires_grad=True)
tensor(1117.6622, grad_fn=<MseLossBackward0>)
tensor([[-0.6986,  0.6736,  1.3360]], requires_grad=True)
tensor(926.2800, grad_fn=<MseLossBackward0>)
tensor([[-0.6639,  0.6955,  1.3610]], requires_grad=True)
tensor(843.5184, grad_fn=<MseLossBackward0>)
tensor([[-0.6410,  0.7096,  1.3776]], requires_grad=True)
tensor(807.6752, grad_fn=<MseLossBackward0>)
tensor([[-0.6258,  0.7184,  1.3886]], requires_grad=True)
tensor(792.0984, grad_fn=<MseLossBackward0>)
tensor([[-0.6157,  0.7239,  1.3961]], requires_grad=True)
tensor(785.2753, grad_fn=<MseLossBackward0>)
tensor([[-0.6089,  0.7