In [15]:
import numpy as np
import pandas as pd
import torch.nn.functional as functional
import torch
# Reading the data
data = pd.read_csv("back.csv")

In [16]:
inputs = data.drop('Temp',axis=1).values
target = data.Temp.values  # target = data['Temp'].values

In [17]:
inputs

array([[ 67,  45,  50],
       [ 50,  35,  40],
       [104,  78,  65],
       [140,  98, 100],
       [ 93,  56,  75],
       [ 79,  43,  55]], dtype=int64)

In [18]:
target

array([ 73,  91,  83,  95,  77, 101], dtype=int64)

In [19]:
inputs = torch.tensor(inputs, dtype=torch.float32)
target = torch.tensor(target, dtype=torch.float32)
target = target.reshape(-1,1)

In [20]:
inputs

tensor([[ 67.,  45.,  50.],
        [ 50.,  35.,  40.],
        [104.,  78.,  65.],
        [140.,  98., 100.],
        [ 93.,  56.,  75.],
        [ 79.,  43.,  55.]])

In [21]:
target

tensor([[ 73.],
        [ 91.],
        [ 83.],
        [ 95.],
        [ 77.],
        [101.]])

In [22]:
w = torch.randn(1, 3, requires_grad=True) # 1 row and 3 column
b = torch.randn(1, requires_grad=True)
print(w)
print(b)

tensor([[-0.1030, -0.2925, -0.8210]], requires_grad=True)
tensor([-1.4993], requires_grad=True)


In [23]:
def model(x):
    return x @ w.t() + b 

In [24]:
prediction = model(inputs)
print(prediction)

tensor([[ -62.6174],
        [ -49.7303],
        [ -88.3985],
        [-126.6940],
        [ -89.0396],
        [ -67.3740]], grad_fn=<AddBackward0>)


In [25]:
mse = functional.mse_loss
loss = mse(prediction,target)
print(loss)

tensor(28773.6152, grad_fn=<MseLossBackward0>)


In [26]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-31242.9023, -20887.2441, -22477.9727]])
tensor([-334.6179])


In [27]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [28]:
for i in range(20):
    pred = model(inputs)
    error=mse(pred, target)
    print(error)
    print(w)
    error.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

tensor(12882.7109, grad_fn=<MseLossBackward0>)
tensor([[ 0.2094, -0.0836, -0.5962]], requires_grad=True)
tensor(6018.5464, grad_fn=<MseLossBackward0>)
tensor([[ 0.4148,  0.0531, -0.4481]], requires_grad=True)
tensor(3053.4158, grad_fn=<MseLossBackward0>)
tensor([[ 0.5499,  0.1425, -0.3504]], requires_grad=True)
tensor(1772.4430, grad_fn=<MseLossBackward0>)
tensor([[ 0.6387,  0.2007, -0.2858]], requires_grad=True)
tensor(1218.9303, grad_fn=<MseLossBackward0>)
tensor([[ 0.6972,  0.2384, -0.2429]], requires_grad=True)
tensor(979.6391, grad_fn=<MseLossBackward0>)
tensor([[ 0.7357,  0.2627, -0.2144]], requires_grad=True)
tensor(876.0737, grad_fn=<MseLossBackward0>)
tensor([[ 0.7610,  0.2782, -0.1952]], requires_grad=True)
tensor(831.1346, grad_fn=<MseLossBackward0>)
tensor([[ 0.7778,  0.2878, -0.1822]], requires_grad=True)
tensor(811.5191, grad_fn=<MseLossBackward0>)
tensor([[ 0.7889,  0.2936, -0.1733]], requires_grad=True)
tensor(802.8423, grad_fn=<MseLossBackward0>)
tensor([[ 0.7962,  0.2